In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
x_arr = np.array([1,2,3,4,5])
y_arr = np.array({2,4,6,8,10})

In [ ]:
print(x_arr)
print(x_arr.ndim)#prints the dimension
x_arr = x_arr.reshape(-1,1)# reshape the array
np.insert(x_arr,0, 1, axis = 1)

[[1]
 [2]
 [3]
 [4]
 [5]]
2


array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [15]:
#assert and vector multiplication, matrix multiplication
#transpose
#print(y_arr)
new_x_arr = np.insert(x_arr,0, 1, axis = 1)
print(new_x_arr)
print(new_x_arr.T)
print(y_arr)

[[1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]]
[[1 1 1 1 1]
 [1 2 3 4 5]]
{2, 4, 6, 8, 10}


In [20]:
result = y_arr @ y_arr.T

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [22]:
np.array([1,2]) @ np.array([4,5])

np.int64(14)

In [21]:
y_arr = np.array([2, 4, 6, 8, 10])

result = y_arr @ y_arr.T
print(result)

220


In [25]:
#np.linalg()
x = int(input("Enter the value"))
assert x>0, "x should be positive"# used to give a condition

In [26]:
class LinearRegression:
    def __init__(self):
        self.weights = None#placeholder for the weights

    def fit(self, x_train, y_train):
        assert x_train.shape[0] == y.shape[0], "Number of samples in x and y must be same"
        assert x_train.shape[0] > 0, "Training data cannot be empty"

        #adding bias term
        x_train = np.insert(x_train, 0, 1, axis = 1)
        self.weights = np.linalg.inv(x_train.T @ x_train) @ x_train.T @ y_train

    def predict(self, x_test):
        if self.weights is None:
            raise ValueError("Model has not been trained yet")

        #adding bias term
        x_test = np.insert(x_test, 0, 1, axis = 1)
        return x_test @ self.weights
        

In [29]:
from sklearn.datasets import make_regression
input, output= make_regression(n_samples = 100, n_features = 1, n_targets = 1)

In [ ]:
LR = LinearRegression()
LR.fit(input, output)
y_pred = LR.predict(input)

NameError: name 'y' is not defined

In [ ]:
plt.scatter(input, output, color = 'blue', label = 'Actual Data')
plt.plot(input, y_pred, color = 'red', label = 'Predicted Line')
plt.title("Linear Regression")
plt.show()